package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping(path="/product") // This means URL's start with /demo (after Application path)
public class MainController {

	@Autowired // This means to get the bean called customerRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ProductRepository productRepository;

	@RequestMapping(value = "/all", method = RequestMethod.GET)
	public List<Product> getAll() {
		return productRepository.findAll();
	}


	@RequestMapping(value = "/create", method = RequestMethod.POST)
	public List<Product> create(@RequestBody Product user) {
		productRepository.save(user);

		return productRepository.findAll();
	}

	@RequestMapping(value = "/delete/{id}", method = RequestMethod.DELETE)
	public List<Product> remove(@PathVariable long id) {
		productRepository.delete(id);

		return productRepository.findAll();
	}

	@PutMapping("/update/{id}")
	public List<Product> updateBook(@RequestBody Product user, @PathVariable Long id) {
		Product currentuser = productRepository.findOne(id);

		currentuser.setName(user.getName());
		//currentuser.setAddress(user.getAddress());
		//currentuser.setCountryCode(user.getCountryCode());

		return productRepository.findAll();
	}
}